
[[dependencies]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[dependencies]]
  branch = "master"
  name = "github.com/lib/pq"

[[dependencies]]
  branch = "master"
  name = "github.com/pressly/chi"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/cobra"
